set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER  x86_64-w64-mingw32-windres)

# shim headers per case-sensitivity (WinSock2.h -> winsock2.h)
set(CMAKE_C_FLAGS_INIT   "-I${MINGW_SHIMS} -DWIN32_LEAN_AND_MEAN")
set(CMAKE_CXX_FLAGS_INIT "-I${MINGW_SHIMS} -DWIN32_LEAN_AND_MEAN")
set(MINGW_SHIMS ${CMAKE_SOURCE_DIR}/cmake/mingw-shims)

# set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
# set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

